# Generated by Django 2.2.4 on 2019-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='donedone',
            field=models.BooleanField(default=False),
        ),
    ]
