# Generated by Django 2.2.4 on 2019-08-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_item_donedone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='donedone',
        ),
    ]
